#include "vm_app.h"
//throw a ton of craziness at the pager
int main() {
	char* p;
	p = (char*) vm_extend();
	char* a;
	a = (char*) vm_extend();
	char* d;
	d = (char*) vm_extend();
	p[0] = 'h';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	a[0] = 'h';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	d[0] = 'h';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	d[1] = 'e';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	d[2] = 'l';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	d[3] = 'l';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	d[4] = 'o';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	p[1] = 'e';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	a[0] = 'h';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	p[2] = 'l';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	d[0] = 'h';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	d[1] = 'e';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	d[2] = 'l';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	d[3] = 'l';
	d[4] = 'o';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	a[0] = 'h';
	p[3] = 'l';
	a[0] = 'h';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	d[0] = 'h';
	d[1] = 'e';
	d[2] = 'l';
	d[3] = 'l';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	d[4] = 'o';
	p[4] = 'o';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	d[0] = 'h';
	d[1] = 'e';
	d[2] = 'l';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	d[3] = 'l';
	d[4] = 'o';
	a[0] = 'h';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	d[0] = 'h';
	d[1] = 'e';
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(p, 16);	
	vm_syslog(d, 5);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	vm_syslog(a, 12);	
	vm_syslog(p, 2);
	d[2] = 'l';
	d[3] = 'l';
	d[4] = 'o';
	vm_syslog(p, 5);
}
